# wget -i download_list.txt --user=username --password=password
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2681.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2681.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2682.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2682.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2683.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2683.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2684.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2684.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2685.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2685.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2686.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2686.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2687.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2687.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2688.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2688.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2689.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2689.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2690.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2690.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2691.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2691.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2692.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2692.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2693.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2693.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2694.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2694.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2695.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2695.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2696.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2696.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2697.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2697.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2698.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2698.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2699.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2699.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2700.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2700.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2701.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2701.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2702.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2702.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2703.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2703.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2704.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2704.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2705.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2705.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2706.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2706.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2707.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2707.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2708.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2708.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2709.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2709.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2710.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2710.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2711.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2711.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2712.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2712.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2713.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2713.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2714.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2714.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2715.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2715.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2716.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2716.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2717.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2717.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2718.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2718.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2719.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2719.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2720.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2720.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2721.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2721.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2722.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2722.weight.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2723.fits
https://datalabs.esa.int/datalabs/5a04f829c35b725b/files/team_workspaces/Euclid-Consortium/data/LSB_reduction/EDF-N/NISP/H/EUC_NIR_H_LSB_ObsID_2723.weight.fits